force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Restaurant__c/Restaurant__c.object-meta.xml
<CustomObject>
    <label>Restaurant</label>
    <nameField>
        <label>Restaurant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Restaurants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Restaurant__c.field-meta.xml
<CustomField>
    <fullName>Restaurant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Restaurant</label>
    <referenceTo>Restaurant__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trainer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trainers</relationshipLabel>
    <relationshipName>Trainers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MailHelper.cls
public class MailHelper {
	public static void sendInvites(List<Participant__c> participants) {
		EmailTemplate et = [SELECT id FROM EmailTemplate WHERE developerName = 'Invite_to_training' LIMIT 1];
		List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
		List<Id> contacts = new List<Id>();
		List<Id> participantIds = new List<Id>();
		for(Participant__c p :participants) {
			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
			mail.saveAsActivity = true;
			mail.setTemplateId(et.id);
			mail.setTargetObjectId(p.Contact_Name__c);
			mail.setWhatId(p.id);
			mail.setSenderDisplayName('Trainer');
			mails.add(mail);
		}
		Messaging.sendEmail(mails);
	}

	public static List<Messaging.SingleEmailMessage> sendParticipantsList(List<Training__c> trainings) {
		EmailTemplate et = [SELECT id FROM EmailTemplate WHERE developerName = 'Participant_List' LIMIT 1];
		List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
		for(Training__c t :trainings) {
			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
			mail.saveAsActivity = true;
			mail.setTemplateId(et.id);
			mail.setTargetObjectId(t.Trainer__c);
			//mail.setWhatId(t.id);
			mail.setSenderDisplayName('Training event');
			PageReference pr = Page.ParticipantsList;
			pr.getParameters().put('trainingId', t.id);
			try {
				Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
				attachment.setFileName('participants.pdf');
				attachment.setContentType('application/pdf');
				attachment.setBody(pr.getContent());
				mail.setFileAttachments(new Messaging.EmailFileAttachment [] { 
									    attachment});
			} catch(VisualforceException e) {
				// handle error
			}

			Messaging.SingleEmailMessage mailToPlace = mail;
			mailToPlace.saveAsActivity = true;
			mailToPlace.setToAddresses(new List<String>{t.Location__r.Email__c});
			mails.add(mailToPlace);

			if(t.Restaurant__c != null) {
				Messaging.SingleEmailMessage mailToRestaurant = mail;
				mailToRestaurant.saveAsActivity = true;
				mailToRestaurant.setToAddresses(new List<String>{t.Restaurant__r.Email__c});
				mails.add(mailToRestaurant);
			}
			mails.add(mail);
		}
		return mails;
	}

	public static List<Messaging.SingleEmailMessage> sendSurveyInvites(List<Participant__c> participants) {
		EmailTemplate et = [SELECT Id, Name, Subject, Body, HtmlValue FROM EmailTemplate WHERE developerName = 'SurveyTemplate' LIMIT 1];
		List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
		for(Participant__c p :participants) {
			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
			mail.setTemplateId(et.id);
			mail.setTargetObjectId(p.Contact_Name__c);
			mail.setWhatId(p.id);
			mail.setSenderDisplayName('Survey');
			mails.add(mail);
		}
        return mails;
	}

	public static List<Messaging.SingleEmailMessage> sendCertificates(List<Participant__c> participants) {
		EmailTemplate et = [SELECT Id, Name, Subject, Body, HtmlValue FROM EmailTemplate WHERE developerName = 'Participant_certificate' LIMIT 1];
		List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
		for(Participant__c p : participants) {
			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
			mail.saveAsActivity = true;
			mail.setTemplateId(et.id);
			mail.setTargetObjectId(p.Contact_Name__c);
			mail.setSenderDisplayName('Certificate');
			////////////////////////
			PageReference pr = Page.Certificate;
            pr.getParameters().put('participantId',  p.id);
            try {
				Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
				attachment.setFileName('certificate.pdf');
				attachment.setContentType('application/pdf');
				attachment.setBody(pr.getContent());
				mail.setFileAttachments(new Messaging.EmailFileAttachment [] {attachment});
            } catch(VisualforceException e) {
                // handle error or send message to admin
            }
			mails.add(mail);
		}
		return mails;
	}
}