force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MailHelperTest.cls
public class MailHelperTest {
    public static void sendMessages(List<Participant__c> participants) {
        EmailTemplate et = [SELECT id FROM EmailTemplate WHERE developerName = 'Invite_to_training' LIMIT 1];
        //Messaging.MassEmailMessage mail = new Messaging.MassEmailMessage();
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        List<Id> contacts = new List<Id>();
        List<Id> participantIds = new List<Id>();
        for(Participant__c p : participants) {
            //contacts.add(p.Contact_Name__c);
            //participantIds.add(p.id);
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        	mail.saveAsActivity = TRUE;
        	mail.setTemplateId(et.id);
        	mail.setTargetObjectId(p.Contact_Name__c);
        	mail.setWhatId(p.id);
        	mail.setSenderDisplayName('Trainer');
            mails.add(mail);
        }
        //mail.saveAsActivity = TRUE;
        //mail.setTemplateId(et.id);
        //mail.setTargetObjectIds(contacts);
        //mail.setWhatIds(participantIds);
        //mail.setSenderDisplayName('Trainer');
        Messaging.sendEmail(mails);
        //Messaging.sendEmail(new Messaging.MassEmailMessage[]{mail});
    } 
}