force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trainer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trainers</relationshipLabel>
    <relationshipName>Trainers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TaskForTrainerSchedule.cls
public with sharing class TaskForTrainerSchedule implements Schedulable {
	public static void execute(System.SchedulableContext ctx) {
		Date d = System.today();
		List<Training__c> trainings = [SELECT id, Trainer__c, Trainer__r.OwnerId FROM Training__c WHERE DAY_ONLY(End_Date__c) = :d];
		if(!trainings.isEmpty()) {
			List<Task> tasks = new List<Task>();
			for(Training__c training :trainings) {
				Task t = new Task();
				t.Subject = 'Fill GPA';
				t.Status = 'Open';
				t.Priority = 'Normal';
				t.WhoId = training.Trainer__c;
				t.OwnerId = training.Trainer__r.OwnerId;
				t.ActivityDate = Date.today() + 2;
				tasks.add(t);
			}
			if(!tasks.isEmpty()) {
				insert tasks;
			}
		}
	}
}