force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trainer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trainers</relationshipLabel>
    <relationshipName>Trainers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FillGPATaskBatch.cls
public with sharing class FillGPATaskBatch implements Database.Batchable<sObject> {

	public List<Training__c> query;
	private List<Task> tasks;

	public List<Training__c> start(Database.BatchableContext bc) {
		tasks = new List<Task>();
		return query;
	}

	public void execute(Database.BatchableContext bc, List<Training__c> trainings) {
		if(!trainings.isEmpty()) {
			for(Training__c training :trainings) {
				Task t = new Task();
				t.Subject = 'Fill GPA';
				t.Status = 'Open';
				t.Priority = 'Normal';
				t.WhatId = training.Trainer__c;
				t.OwnerId = t.OwnerId;
				tasks.add(t);
			}
		}
	}

	public void finish(Database.BatchableContext bc) {
		if(tasks.isEmpty()) {
			insert tasks;
		}
	}

}