force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trainer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trainers</relationshipLabel>
    <relationshipName>Trainers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SendListParticipantsSchedule.cls
public class SendListParticipantsSchedule implements Schedulable {
    public static void execute(System.SchedulableContext ctx) {
        Date d = System.today() + 5;
        List<Training__c> trainings = [SELECT id, Start_Date__c, End_Date__c, Trainer__c 
                                      FROM Training__c
                                      WHERE DAY_ONLY(Start_Date__c) = :d];
        if(!trainings.isEmpty()) {
            SendListParticipantsBatch slpb = new SendListParticipantsBatch();
            slpb.query = trainings;
            Id listBatchId = Database.executeBatch(slpb);
        }
    }
}