force-app/main/default/objects/Contact/recordTypes/Participants.recordType-meta.xml
<RecordType>
    <fullName>Participants</fullName>
    <active>true</active>
    <description>RT for participants. They cannot be a trainer</description>
    <label>Participants</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Trainers.recordType-meta.xml
<RecordType>
    <fullName>Trainers</fullName>
    <active>true</active>
    <description>RT for trainers. This type can be a trainer</description>
    <label>Trainers</label>
</RecordType>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/GPA__c.field-meta.xml
<CustomField>
    <fullName>GPA__c</fullName>
    <label>GPA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Registration_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Registration_Date_Time__c</fullName>
    <label>Registration Date-Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>In Queue</fullName>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Restaurant__c/Restaurant__c.object-meta.xml
<CustomObject>
    <label>Restaurant</label>
    <nameField>
        <label>Restaurant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Restaurants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Max_participants_quantity__c.field-meta.xml
<CustomField>
    <fullName>Max_participants_quantity__c</fullName>
    <defaultValue>5</defaultValue>
    <label>Max participants quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Restaurant__c.field-meta.xml
<CustomField>
    <fullName>Restaurant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Restaurant</label>
    <referenceTo>Restaurant__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trainer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trainers</relationshipLabel>
    <relationshipName>Trainers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Training_Course__c.field-meta.xml
<CustomField>
    <fullName>Training_Course__c</fullName>
    <label>Training Course</label>
    <referenceTo>Training_Course__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Course__c/Training_Course__c.object-meta.xml
<CustomObject>
    <label>Training Course</label>
    <nameField>
        <label>Training Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/tests/CertificateController_test.cls
@IsTest
public with sharing class CertificateController_test {
    @TestSetup
    static void makeData() {

		Account a = new Account(name = 'Account1', billingcity = 'New York', billingcountry = 'USA');
		insert a;
        
        Contact trainer = new Contact(firstname = 'Mark', lastname = 'Benioff', accountId = a.id);
        //c.OwnerId = a.id;
        Id devRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Trainers').getRecordTypeId();
        trainer.RecordTypeId = devRecordTypeId;
		insert trainer;
        
        Training_Course__c trC = new Training_Course__c(Name = 'TEST COURSE', Description__c = 'DESCRIPTION');
        insert trC;
        
		Location__c l = new Location__c(Name = 'Location', Email__c = 'location@org.com');
		insert l;

		Restaurant__c r = new Restaurant__c(Name = 'Restaurant', Email__c = 'Restaurant@org.com');
		insert r;

		Training__c t = new Training__c();
		t.Training_Course__c = trC.id;
		t.Start_Date__c = Datetime.now();
		t.End_Date__c = Datetime.now();
		t.Status__c = 'Active';
		t.Max_participants_quantity__c = 10;
		t.Restaurant__c = r.id;
        t.Location__c = l.id;
        t.Trainer__c = trainer.id;
        insert t;

		Contact c = new Contact(firstname = 'first', lastname = 'last', accountId = a.id, Email = 'contact@test.org');
		insert c;

        List<Participant__c> lp = new List<Participant__c>();
        for(Integer i = 0; i < 10; i++) {
            Participant__c p = new Participant__c();
            p.Contact_Name__c = c.id;
            p.Training__c = t.id;
            p.Registration_Date_Time__c = Datetime.now();
            lp.add(p);
        }
		insert lp;
    }

    @IsTest
    static void isSignaturePresentTest() {
        CertificateController c = new CertificateController();
        System.assertEquals(false, c.getIsSignaturePresent(), 'Signature file not upload');
    }

    @IsTest
    static void getUrlTest() {
        System.assertEquals(System.URL.getSalesforceBaseUrl().toExternalForm(), CertificateController.getUrl(), 'URLs not equals');      
    }

    @IsTest
    static void getGPATest(){
        Training__c t = [SELECT id FROM Training__c LIMIT 1];
        List<Participant__c> lp = CertificateController.getGPA(t.id);
        System.assertEquals(10, lp.size(), 'get GPA error');    
    }

    @IsTest
    static void setGPATest() {
        List<Participant__c> lp1;
        System.assertEquals('Fail', CertificateController.setGPA(lp1), 'Logic of code error');
        List<Participant__c> lp2 = new List<Participant__c>();
        for(Participant__c p : [SELECT id, Status__c FROM Participant__c]) {
            p.GPA__c = 5;
            lp2.add(p);
        }
        System.assertEquals('Successfuly', CertificateController.setGPA(lp2), 'Update GPA DML exception');     
    }

    @IsTest
    static void getParticipantsTest() {
        Test.startTest();
        Training__c t = [SELECT id, Trainer__c FROM Training__c LIMIT 1];
        Participant__c p = [SELECT id FROM Participant__c WHERE Training__c = :t.id LIMIT 1];

        PageReference myVfPage = Page.Certificate;
        Test.setCurrentPage(myVfPage);
        ApexPages.currentPage().getParameters().put('trainingId', t.Id);
    
        CertificateController c = new CertificateController();
        List<Participant__c> part1 = c.getParticipants();
        System.assertEquals(10, part1.size(), 'Get participants assert error');

        ApexPages.currentPage().getParameters().put('participantId', p.Id);
        List<Participant__c> part2 = c.getParticipants();
        System.assertEquals(1, part2.size(), 'Get participants assert error');

        Test.stopTest();
    }
}