force-app/main/default/objects/Contact/recordTypes/Participants.recordType-meta.xml
<RecordType>
    <fullName>Participants</fullName>
    <active>true</active>
    <description>RT for participants. They cannot be a trainer</description>
    <label>Participants</label>
</RecordType>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/GPA__c.field-meta.xml
<CustomField>
    <fullName>GPA__c</fullName>
    <label>GPA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trainer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trainers</relationshipLabel>
    <relationshipName>Trainers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Training_Course__c.field-meta.xml
<CustomField>
    <fullName>Training_Course__c</fullName>
    <label>Training Course</label>
    <referenceTo>Training_Course__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Course__c/Training_Course__c.object-meta.xml
<CustomObject>
    <label>Training Course</label>
    <nameField>
        <label>Training Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CertificateController.cls
public class CertificateController {
    
    private boolean isSignatureReceived;
    private String trainingId;
    private String trainerSignature;
    
    public CertificateController () {
    }
	
    public boolean getIsSignaturePresent() {
        return !(trainerSignature == '' || trainerSignature == null);
    }
    
    @AuraEnabled
    public static String getUrl() {
        return System.URL.getSalesforceBaseUrl().toExternalForm();
    }
    
    @AuraEnabled
    public static String generatePDF(String trainingId) {
        List<Participant__c> participants = [SELECT id, Contact_Name__c, Contact_Name__r.FirstName, Contact_Name__r.LastName FROM Participant__c WHERE Training__c = :trainingId];
        List<ContentVersion> cvs = new List<ContentVersion>();
        
        for(Participant__c p: participants) {
            ContentVersion cv = new ContentVersion();

            PageReference pr = Page.Certificate;
            pr.getParameters().put('participantId',  p.id);
            Blob body;
            try {
                body = pr.getContentAsPdf();
            } catch(VisualforceException e) {
                // handle error
                return 'Cannot generate PDF';
            }
            cv.Title = 'Cerifcate_' + p.Contact_Name__r.FirstName + '_' + p.Contact_Name__r.LastName;
            cv.PathOnClient = 'Certificate_' + p.Contact_Name__r.FirstName + '_' + p.Contact_Name__r.LastName + '.pdf';
            cv.VersionData = body;
            cv.FirstPublishLocationId = p.Contact_Name__c;
            cvs.add(cv);
        }
        upsert cvs;
        return 'Success';
    }

    public List<Participant__c> getParticipants() {       
		String participantId = ApexPages.currentPage().getParameters().get('participantId');
        String trainingId = ApexPages.currentPage().getParameters().get('trainingId');
        List<Participant__c> participants;

        // get signature
        List<Training__c> t = [SELECT Trainer__c, Trainer__r.FirstName, Trainer__r.LastName FROM Training__c WHERE id = :trainingId];       
        if(!t.isEmpty()) {

            ContentWorkspace ws = [SELECT Id, RootContentFolderId FROM ContentWorkspace WHERE Name = 'Signatures' LIMIT 1];
                String filename = t.get(0).Trainer__r.FirstName + '_' + t.get(0).Trainer__r.LastName;
                List<ContentDocumentLink> cdLink = [SELECT id, ContentDocument.LatestPublishedVersionID
                                                FROM ContentDocumentLink
                                                WHERE linkedEntityId = :ws.Id AND ContentDocument.Title = :filename LIMIT 1];
                if(!cdLink.isEmpty()) {
                    trainerSignature = cdLink.get(0).ContentDocument.LatestPublishedVersionID;                                                    
                }
        }
        // get signature
        
        if(participantId == null) {
           participants = [
            SELECT Contact_Name__r.FirstName, Contact_Name__r.LastName, 
            Training__r.Start_Date__c, Training__r.End_Date__c,
            GPA__c,
            Training__r.Training_Course__r.Name,
            Training__r.Training_Course__r.Description__c,
            Training__r.Location__r.Billing_City__c,
            Training__r.CreatedById,
            Training__r.Trainer__r.FirstName,
            Training__r.Trainer__r.LastName   
            FROM Participant__c WHERE Training__c = :trainingId];
        } 
        else {
            participants = [
            SELECT Contact_Name__r.FirstName, Contact_Name__r.LastName, 
            Training__r.Start_Date__c, Training__r.End_Date__c,
            GPA__c,
            Training__r.Training_Course__r.Name,
            Training__r.Training_Course__r.Description__c,
            Training__r.Location__r.Billing_City__c,
            Training__r.CreatedById,
            Training__r.Trainer__r.FirstName,
            Training__r.Trainer__r.LastName 
            FROM Participant__c WHERE Id = :participantId];
        }
        return participants;
    }
    
	@AuraEnabled
    public static List<Participant__c> getGpa(String trId) {
		List<Participant__c> participants;
        if(trId != null) {
        	participants = [
			SELECT Contact_Name__r.FirstName, Contact_Name__r.LastName, 
			Training__r.Start_Date__c, Training__r.End_Date__c,
			GPA__c
			FROM Participant__c WHERE Training__c = :trId];
        }
		return participants;
    }
    
    @AuraEnabled
    public static String setGpa(Participant__c[] participants) {
        if(participants != null) {
			update participants;
            return 'Successfuly';
        }
        return 'Fail';
    }
        
    public String getSignature() {
        return System.URL.getSalesforceBaseUrl().toExternalForm() + '/sfc/servlet.shepherd/version/download/' + trainerSignature;
    }
}