force-app/main/default/objects/Contact/recordTypes/Trainers.recordType-meta.xml
<RecordType>
    <fullName>Trainers</fullName>
    <active>true</active>
    <description>RT for trainers. This type can be a trainer</description>
    <label>Trainers</label>
</RecordType>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Max_participants_quantity__c.field-meta.xml
<CustomField>
    <fullName>Max_participants_quantity__c</fullName>
    <defaultValue>5</defaultValue>
    <label>Max participants quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trainer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trainers</relationshipLabel>
    <relationshipName>Trainers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Training_Course__c.field-meta.xml
<CustomField>
    <fullName>Training_Course__c</fullName>
    <label>Training Course</label>
    <referenceTo>Training_Course__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Course__c/Training_Course__c.object-meta.xml
<CustomObject>
    <label>Training Course</label>
    <nameField>
        <label>Training Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/tests/CreateTaskForTrainerSchedule_Test.cls
@isTest
public with sharing class CreateTaskForTrainerSchedule_Test {
    @TestSetup
    static void makeData() {

		Account a = new Account(name = 'Account1', billingcity = 'New York', billingcountry = 'USA');
		insert a;

        Contact c = new Contact(firstname = 'Trainer', lastname = 'Trainer surname', accountId = a.id);
        //c.OwnerId = a.id;
        Id devRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Trainers').getRecordTypeId();
        c.RecordTypeId = devRecordTypeId;
		insert c;

        Training_Course__c trC = new Training_Course__c(Name = 'TEST COURSE', Description__c = 'DESCRIPTION');
        insert trC;
        
		Training__c t = new Training__c();
		t.Training_Course__c = trC.id;
		t.Start_Date__c = Datetime.now();
		t.End_Date__c = Datetime.now();
		t.Status__c = 'Active';
		t.Max_participants_quantity__c = 10;
        t.Trainer__c = c.id;
        insert t;
    }
    public final static String CRON_EXP = '0 0 0 ? * * *';

    @IsTest
    static void doTestTaskCreate() {
        
        Test.startTest();
        Date d = System.today();
		List<Training__c> trainings = [SELECT id, Trainer__c, Start_Date__c, End_Date__c, Trainer__r.OwnerId FROM Training__c];
        TaskFortrainerSchedule sh1 = new TaskFortrainerSchedule();
        system.schedule('Test add task', CRON_EXP, sh1); 
        Test.stopTest();

        List<Task> t = [SELECT id, Subject, Status, Priority, WhoId, OwnerId FROM Task];
        System.assertEquals(false, t.isEmpty(), 'Task not created');
        
    }
}